version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dependencies/dependabot
      - dependencies/npm
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dependencies/dependabot
      - dependencies/github-actions
